### ISSUE TITLE
[Feature Request]: Don't translate special purpose artists

### ISSUE THREAD

**Issue by Nero-A** [musicbrainz/picard-plugins#237] opened 2019-09-20 11:12 UTC
In MusicBrainz there are [some special purpose artists](https://musicbrainz.org/doc/Style/Unknown_and_untitled/Special_purpose_artist) like [Various Artists](https://musicbrainz.org/artist/89ad4ac3-39f7-470e-963a-56509c546377) and [[unknown]](https://musicbrainz.org/artist/125ec42a-7229-4250-afc5-e057484327fe).

Whereas _Various Artists_ is normally used on release-level (compilations), [unknown] is used on track level when the artist is not known.

Even if an artist is unknown or not specified detailed enough it is normally credited with a specific term, e.g. "singing children".

In Picard there is the option "Metadata" / "Translate artist names to local where possible".
This option is activated by default (if I'm right) and is basically useful, e.g. for translating Asian artist names to Latin name-variants. I'd like to keep this option active for me.

If this option is activated, it will also translate special purpose artists, at least _[unknown]_, e.g. to "[unbekannt]" (German). In this case the "credited as" gets lost.
In my example _[unknown] as "singing children"_ will be translated to artist _[unbekannt]_.
It the option is deactivated the artist name _"singing children"_ will be kept.
It's not good to lose the credited-as-name for special purpose artists by translating. The original credited-as-name should be kept here.

There is already a special processing for _Various artists_ but it would be fine to have the option to avoid translating for _[unknown]_ (and other special purpose artists).

**Comment by phw** [comment] 2019-09-20 14:50
Please report issues regarding Picard to https://tickets.metabrainz.org/projects/PICARD/

In this case I think this is a duplicate of https://tickets.metabrainz.org/browse/PICARD-758 and unrelated to whether this is a special purpose artist or not. I also wonder whether you have "use standardized artist names" active.

**Closed as completed by phw** 2019-09-20 14:50 UTC

**Comment by Nero-A** [comment] 2019-09-21 01:33
https://tickets.metabrainz.org/browse/PICARD-1611

BTW: For me it's not a duplicate of https://tickets.metabrainz.org/browse/PICARD-758 and I don't think this is the same problem.
